services:
  hasheous-taskrunner:
    container_name: hasheous-taskrunner
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - hasheous-taskrunner
    volumes:
      - hasheous-taskrunner:/root/.hasheous-taskrunner
    environment:
      - HostAddress=https://hasheous.org/
      - APIKey=
      - ollama_url=
volumes:
  hasheous-taskrunner:
